# Form implementation generated from reading ui file 'guifinal1.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(323, 424)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"selection-color: rgb(85, 170, 255);\n"
"gridline-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_bread = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_bread.setGeometry(QtCore.QRect(20, 60, 73, 22))
        self.combo_bread.setAcceptDrops(True)
        self.combo_bread.setAutoFillBackground(False)
        self.combo_bread.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.combo_bread.setObjectName("combo_bread")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.combo_bread.addItem("")
        self.label_Weight = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Weight.setGeometry(QtCore.QRect(120, 40, 55, 16))
        self.label_Weight.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_Weight.setObjectName("label_Weight")
        self.text_weight = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_weight.setGeometry(QtCore.QRect(110, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_weight.setFont(font)
        self.text_weight.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.text_weight.setObjectName("text_weight")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(20, 0, 281, 21))
        self.label_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label_title.setObjectName("label_title")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 60, 93, 28))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 260, 241, 41))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_information = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_information.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_information.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_information.setObjectName("label_information")
        self.label_life = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_life.setGeometry(QtCore.QRect(10, 130, 55, 16))
        self.label_life.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_life.setObjectName("label_life")
        self.text_lifespan = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_lifespan.setGeometry(QtCore.QRect(10, 150, 71, 21))
        self.text_lifespan.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.text_lifespan.setObjectName("text_lifespan")
        self.label_status_weight = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_status_weight.setGeometry(QtCore.QRect(180, 130, 101, 16))
        self.label_status_weight.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_status_weight.setObjectName("label_status_weight")
        self.text_status_weight = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_status_weight.setGeometry(QtCore.QRect(180, 150, 101, 21))
        self.text_status_weight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_status_weight.setObjectName("text_status_weight")
        self.label_goingOver = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_goingOver.setGeometry(QtCore.QRect(10, 180, 121, 16))
        self.label_goingOver.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_goingOver.setObjectName("label_goingOver")
        self.text_goinover = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_goinover.setGeometry(QtCore.QRect(10, 200, 91, 21))
        self.text_goinover.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.text_goinover.setObjectName("text_goinover")
        self.label_goinunder = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_goinunder.setGeometry(QtCore.QRect(180, 180, 121, 16))
        self.label_goinunder.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_goinunder.setObjectName("label_goinunder")
        self.text_goinunder = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_goinunder.setGeometry(QtCore.QRect(180, 200, 101, 21))
        self.text_goinunder.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.text_goinunder.setObjectName("text_goinunder")
        self.label_resulr_overweight = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_resulr_overweight.setGeometry(QtCore.QRect(10, 310, 241, 16))
        self.label_resulr_overweight.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_resulr_overweight.setObjectName("label_resulr_overweight")
        self.label_result_underweight = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result_underweight.setGeometry(QtCore.QRect(10, 340, 251, 16))
        self.label_result_underweight.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_result_underweight.setObjectName("label_result_underweight")
        self.label_breed = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_breed.setGeometry(QtCore.QRect(20, 40, 55, 16))
        self.label_breed.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_breed.setObjectName("label_breed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 323, 27))
        self.menubar.setObjectName("menubar")
        self.menuyuot_dog_right_weight = QtWidgets.QMenu(parent=self.menubar)
        self.menuyuot_dog_right_weight.setObjectName("menuyuot_dog_right_weight")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuyuot_dog_right_weight.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combo_bread.setItemText(0, _translate("MainWindow", "Select"))
        self.combo_bread.setItemText(1, _translate("MainWindow", "Labrador Retriever"))
        self.combo_bread.setItemText(2, _translate("MainWindow", "Bulldog"))
        self.combo_bread.setItemText(3, _translate("MainWindow", "German Shepherd    "))
        self.combo_bread.setItemText(4, _translate("MainWindow", "Chihuahua"))
        self.combo_bread.setItemText(5, _translate("MainWindow", "Poodle"))
        self.combo_bread.setItemText(6, _translate("MainWindow", "Saint Berbard"))
        self.combo_bread.setItemText(7, _translate("MainWindow", "Pomeranian"))
        self.label_Weight.setText(_translate("MainWindow", "Weight"))
        self.text_weight.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_title.setText(_translate("MainWindow", "Chose your breed and ad the weight of your dog "))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label_information.setText(_translate("MainWindow", "Information"))
        self.label_life.setText(_translate("MainWindow", "Lifespan"))
        self.text_lifespan.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_status_weight.setText(_translate("MainWindow", "Status of weight"))
        self.text_status_weight.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_goingOver.setText(_translate("MainWindow", "You are going over"))
        self.label_goinunder.setText(_translate("MainWindow", "You are goin under"))
        self.label_resulr_overweight.setText(_translate("MainWindow", "You dog is over weight plese visit a vet"))
        self.label_result_underweight.setText(_translate("MainWindow", "Your dog is under weigth plese visit a vet"))
        self.label_breed.setText(_translate("MainWindow", "Breed"))
        self.menuyuot_dog_right_weight.setTitle(_translate("MainWindow", "Your dog right weight"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
